Модель и текстура монетки
denismaster/YetAnotherGame pull request #18
Opened 2019-01-13 18:07 UTC by denismaster

Closes #9

2019-01-14 09:21 UTC, denismaster commented
Сделал force-push, т.к. сделал ссылку на неверную задачу

2019-01-15 11:07 UTC, MikhailCrimea requested changes
в проекте лишний файл от импорта монетки (coin.max)

2019-01-16 15:15 UTC, MikhailCrimea commented on YetAnotherGame/Assets/Scenes/SampleScene.unity
> -  speed: 6
точно в игре все хорошо? ощущение, что пропали объекты speed, gravity и т.д.

2019-01-16 15:15 UTC, MikhailCrimea commented on YetAnotherGame/ProjectSettings/ProjectVersion.txt
> +m_EditorVersion: 2018.3.0f2
мы с Никитой файл этот выносили из-под контроля версий, теперь я понял о чем речь идет

2019-01-16 15:15 UTC, MikhailCrimea requested changes
оставил 2 коммента

2019-01-16 15:29 UTC, MikhailCrimea commented on YetAnotherGame/Assets/Scenes/SampleScene.unity
> -  speed: 6
все нормально, но странное удаление какое-то
хорошо бы потом подумать, что это значит

2019-01-16 15:30 UTC, MikhailCrimea submitted a review, later dismissed

2019-01-16 15:57 UTC, MikhailCrimea approved these changes

2019-01-16 15:57 UTC, merged