#3,#19: add person prefab, fixed camera, fixed camera bug from #19
denismaster/YetAnotherGame pull request #21
Opened 2019-01-20 16:32 UTC by MikhailCrimea

review pls again

2019-01-21 08:12 UTC, denismaster requested changes

2019-01-21 08:12 UTC, denismaster commented on YetAnotherGame/Assets/Scripts/Controllers/PlayerController.cs
> +    [SerializeField] private float m_moveSpeed = 2;
Что за префикс `m_` впереди каждого поля?

2019-01-26 13:34 UTC, MikhailCrimea commented on YetAnotherGame/Assets/Scripts/Controllers/PlayerController.cs
> +    [SerializeField] private float m_moveSpeed = 2;
Убрал, в некоторых code style так помечаются приватные члены класса

2019-01-26 14:54 UTC, denismaster approved these changes

2019-01-26 15:31 UTC, merged