добавление-врщения-камеры-и-модельки-персонажа
denismaster/YetAnotherGame pull request #7
Opened 2019-01-05 13:36 UTC by Justgoodwin

2019-01-05 15:12 UTC, denismaster approved these changes
Коммиты лучше писать на английском. А так норм вроде. Задачу можно не закрывать заранее, а просто сделать в пулл-реквесте ссылку на нее.

2019-01-06 12:16 UTC, MikhailCrimea reviewed
Что хочется изменить:
- имя объекта на сцене MaleFreeSimpleMovement1, как бы важно чтобы объекты носили разумные и понятные имена, типа player
- давайте держать пустой область ошибок в редакторе, если есть warning'и, от них сразу нужно избавляться (сейчас 524 warning'а, а мастере 0)
- описание таска нужно обновить, т.к. помимо модельки игрока появилась земля и трава и почему-то с озером). Хочется все фичи видеть описанными в таске.
- появился какой-то объект Coins Counter внутри персонажа, хотя таск не для подсчета собранных монеток, попробовал пособирать, не отображается и непонятно в каком статусе фича с монеткой.
это должен быть отдельный таск, не нужно делать заранее заготовки для будущей фичи.
- что такое EventSystem и почему он расположен в таком удалении от сцены
- почему-то составные элементы конечностей человека отображаются где-то в небе, хотя должны быть на самом человеке

2019-01-07 14:32 UTC, denismaster commented
@Justgoodwin смерджи плиз

2019-01-11 13:18 UTC, denismaster requested changes
@Justgoodwin необходимо почистить ветку от модели персонажа, монеток и камеры. Оставить только террейн с горами и озерами.

2019-01-13 16:07 UTC, denismaster commented
Closed as invalid

2019-01-13 16:07 UTC, closed without merging